spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?characterEncoding=utf-8
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: start,wall,log4j
    #最大活跃数
    maxActiv: 20
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      min-idle: 1
      test-while-idle: true
      #初始化数量
      initial-size: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    tomcat:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-on-borrow: false
      test-on-return: false
  jpa:
      properties: 
        hibernate:
          show_sql:true
          format_sql:true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp   
       
      