spring:
  datasource:
    url: jdbc:mysql:///test?characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    password: root
    username: root
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy